#include "../ecf.h"

#define DSREG_E_DEVICE_MESSAGE_FORMAT_ERROR     0x801C0001
#define DSREG_E_DEVICE_AUTHENTICATION_ERROR     0x801C0002
#define DSREG_E_DEVICE_AUTHORIZATION_ERROR      0x801C0003
#define DSREG_E_DEVICE_INTERNALSERVICE_ERROR    0x801C0006
#define DSREG_E_DISCOVERY_REDIRECTION_NOT_TRUST 0x801C000B
#define DSREG_E_DISCOVERY_FAILED                0x801C000C
#define DSREG_E_DEVICE_REGISTRATION_QUOTA_EXCCE 0x801C000E
#define DSREG_E_DEVICE_REQUIRES_REBOOT          0x801C000F
#define DSREG_E_DEVICE_AIK_VALIDATION_ERROR     0x801C0010
#define DSREG_E_DEVICE_ATTESTATION_ERROR        0x801C0011
#define DSREG_E_DISCOVERY_BAD_MESSAGE_ERROR     0x801C0012
#define DSREG_E_TENANTID_NOT_FOUND              0x801C0013
#define DSREG_E_USERSID_NOT_FOUND               0x801C0014
#define DSREG_DEVICE_NOT_DOMAIN_JOINED          0x801C0015
#define DSREG_MISSING_JOIN_INFO                 0x801C0016
#define DSREG_JOIN_REQUIRED                     0x801C001B
#define DSREG_E_SERVER_WAIT_TIMEOUT             0x801C001C
#define DSREG_AUTOJOIN_ADCONFIG_READ_FAILED     0x801C001D
#define DSREG_AUTOJOIN_CREATE_EVENT_FAILED      0x801C001E
#define DSREG_AUTOJOIN_DISC_WAIT_TIMEOUT        0x801C001F
#define DSREG_AUTOJOIN_DISC_WAIT_FAILED         0x801C0020
#define DSREG_AUTOJOIN_DISC_FAILED              0x801C0021
#define DSREG_MISSING_DEVICE_ID_IN_TOKEN        0x801C0022
#define DSREG_MFA_REQUIRED                      0x801C0023
#define DSREG_USER_NOT_FOUND                    0x801C0024
#define DSREG_SERVER_BUSY                       0x801C0025
#define DSREG_NGC_KEY_ALREADY_EXISTS            0x801C0026
#define DSREG_BAD_DIRECTORY_REQUEST             0x801C0027
#define DSREG_DIRECTORY_REPLICA_UNAVAILABLE     0x801C0028
#define DSREG_DIRECTORY_REQUEST_THROTTLED       0x801C0029
#define DSREG_DIRECTORY_REQUEST_DENIED          0x801C002A
#define DSREG_DEVICE_KEY_NOACCESS               0x801C002B
#define DSREG_DEVICE_KEY_MISSING                0x801C002C
#define DSREG_JSON_REQUEST_FAILED               0x801C002D
#define DSREG_JSON_REQUEST_NODATA               0x801C002E
#define DSREG_E_AADPLUGIN_PRT_NOTFOUND          0x801C0030
#define DSREG_AUTH_TOKEN_NOT_FOUND              0x801C0031
#define DSREG_INVALID_RESPONSE                  0x801C03E9
#define DSREG_E_NGC_AUTHORIZATION_ERROR         0x801C03EA
#define DSREG_E_NGC_UNEXPECTED_HTTP_STATUS      0x801C03EB
#define DSREG_E_NGC_INTERNAL_SERVER_ERROR       0x801C03EC
#define DSREG_E_NGC_INVALID_REQUEST             0x801C03ED
#define DSREG_E_NGC_ATTESTATION_ERROR           0x801C03EE
#define DSREG_E_NGC_AIK_CERT_RENEW              0x801C03EF
#define DSREG_E_NGC_KEY_NOT_FOUND               0x801C03F0
#define DSREG_E_UPN_NOT_FOUND                   0x801C03F1
#define DSREG_E_DIRECTORY_FAILURE               0x801C03F2
#define DSREG_E_DEVICE_NOT_FOUND                0x801C03F3
#define DSREG_E_CXH_DEVICE_NOT_JOINED           0x801C03F4
#define DSREG_E_CXH_NO_SCENARIO_FOUND           0x801C03F5
#define DSREG_E_NGC_CERT_NO_ENTSSO              0x801C03F6
#define DSREG_E_NGC_INVALID_CONTAINER_OPTIONS   0x801C03F7
#define DSREG_E_NO_CORE_WINDOW                  0x801C044C
#define DSREG_E_USER_TOKEN_ERROR                0x801C044D
#define DSREG_E_USER_INPUT_WAIT_FAILED          0x801C044E
#define DSREG_E_USER_TOKEN_REQUEST_CANCELLED    0x801C044F
#define DSREG_E_DEVICE_NOT_JOINED               0x801C0450

static ErrorCodeItem ec_dsreg_items[] = {
    REGCODE(DSREG_E_DEVICE_MESSAGE_FORMAT_ERROR)
    REGCODE(DSREG_E_DEVICE_AUTHENTICATION_ERROR)
    REGCODE(DSREG_E_DEVICE_AUTHORIZATION_ERROR)
    REGCODE(DSREG_E_DEVICE_INTERNALSERVICE_ERROR)
    REGCODE(DSREG_E_DISCOVERY_REDIRECTION_NOT_TRUST)
    REGCODE(DSREG_E_DISCOVERY_FAILED)
    REGCODE(DSREG_E_DEVICE_REGISTRATION_QUOTA_EXCCE)
    REGCODE(DSREG_E_DEVICE_REQUIRES_REBOOT)
    REGCODE(DSREG_E_DEVICE_AIK_VALIDATION_ERROR)
    REGCODE(DSREG_E_DEVICE_ATTESTATION_ERROR)
    REGCODE(DSREG_E_DISCOVERY_BAD_MESSAGE_ERROR)
    REGCODE(DSREG_E_TENANTID_NOT_FOUND)
    REGCODE(DSREG_E_USERSID_NOT_FOUND)
    REGCODE(DSREG_DEVICE_NOT_DOMAIN_JOINED)
    REGCODE(DSREG_MISSING_JOIN_INFO)
    REGCODE(DSREG_JOIN_REQUIRED)
    REGCODE(DSREG_E_SERVER_WAIT_TIMEOUT)
    REGCODE(DSREG_AUTOJOIN_ADCONFIG_READ_FAILED)
    REGCODE(DSREG_AUTOJOIN_CREATE_EVENT_FAILED)
    REGCODE(DSREG_AUTOJOIN_DISC_WAIT_TIMEOUT)
    REGCODE(DSREG_AUTOJOIN_DISC_WAIT_FAILED)
    REGCODE(DSREG_AUTOJOIN_DISC_FAILED)
    REGCODE(DSREG_MISSING_DEVICE_ID_IN_TOKEN)
    REGCODE(DSREG_MFA_REQUIRED)
    REGCODE(DSREG_USER_NOT_FOUND)
    REGCODE(DSREG_SERVER_BUSY)
    REGCODE(DSREG_NGC_KEY_ALREADY_EXISTS)
    REGCODE(DSREG_BAD_DIRECTORY_REQUEST)
    REGCODE(DSREG_DIRECTORY_REPLICA_UNAVAILABLE)
    REGCODE(DSREG_DIRECTORY_REQUEST_THROTTLED)
    REGCODE(DSREG_DIRECTORY_REQUEST_DENIED)
    REGCODE(DSREG_DEVICE_KEY_NOACCESS)
    REGCODE(DSREG_DEVICE_KEY_MISSING)
    REGCODE(DSREG_JSON_REQUEST_FAILED)
    REGCODE(DSREG_JSON_REQUEST_NODATA)
    REGCODE(DSREG_E_AADPLUGIN_PRT_NOTFOUND)
    REGCODE(DSREG_AUTH_TOKEN_NOT_FOUND)
    REGCODE(DSREG_INVALID_RESPONSE)
    REGCODE(DSREG_E_NGC_AUTHORIZATION_ERROR)
    REGCODE(DSREG_E_NGC_UNEXPECTED_HTTP_STATUS)
    REGCODE(DSREG_E_NGC_INTERNAL_SERVER_ERROR)
    REGCODE(DSREG_E_NGC_INVALID_REQUEST)
    REGCODE(DSREG_E_NGC_ATTESTATION_ERROR)
    REGCODE(DSREG_E_NGC_AIK_CERT_RENEW)
    REGCODE(DSREG_E_NGC_KEY_NOT_FOUND)
    REGCODE(DSREG_E_UPN_NOT_FOUND)
    REGCODE(DSREG_E_DIRECTORY_FAILURE)
    REGCODE(DSREG_E_DEVICE_NOT_FOUND)
    REGCODE(DSREG_E_CXH_DEVICE_NOT_JOINED)
    REGCODE(DSREG_E_CXH_NO_SCENARIO_FOUND)
    REGCODE(DSREG_E_NGC_CERT_NO_ENTSSO)
    REGCODE(DSREG_E_NGC_INVALID_CONTAINER_OPTIONS)
    REGCODE(DSREG_E_NO_CORE_WINDOW)
    REGCODE(DSREG_E_USER_TOKEN_ERROR)
    REGCODE(DSREG_E_USER_INPUT_WAIT_FAILED)
    REGCODE(DSREG_E_USER_TOKEN_REQUEST_CANCELLED)
    REGCODE(DSREG_E_DEVICE_NOT_JOINED)
};

static LPTSTR dsreg_code2msg(DWORD dwCode)
{
    LPTSTR result = NULL;

    if (hModCertUtil)
    {
        UINT uID = dwCode & 0xFFFF;

        if (uID < 0x3E9)
        {
            uID += 0xCE00;
        }
        else if (uID < 0x44C)
        {
            uID += 0xCC00;
        }
        else
        {
            uID += 0xCA00;
        }

        if (0 != uID)
        {
            result = (LPTSTR)LocalAlloc(LPTR, MAX_MSG_LEN * sizeof (TCHAR));
            if (result)
            {
                LoadString(hModCertUtil, uID, result, MAX_MSG_LEN);
            }
        }
    }

    return result;
}

static void dsreg_freemsg(LPTSTR lpMessage)
{
    LocalFree(lpMessage);
}

void EcRegDsreg(ErrorCodeSet *pecs)
{
    pecs->lpName = TEXT("DSREG");
    pecs->pfnMessageFromCode = dsreg_code2msg;
    pecs->pfnFreeMessage = dsreg_freemsg;
    pecs->items = ec_dsreg_items;
    pecs->dwCodeCount = ARRAYSIZE(ec_dsreg_items);
}

void EcUnregDsreg()
{
    /* Ignore */
}

