#include "../ecf.h"

#define CMN_E_NOT_YET_INITIALIZED               0x82AA0000
#define CMN_E_BAD_XML                           0x82AA0001
#define CMN_E_ALREADY_EXISTS                    0x82AA0002
#define CMN_E_INTEGER_OVERFLOW                  0x82AA0003
#define CMN_E_INTEGER_UNDERFLOW                 0x82AA0004
#define CMN_E_ROLLBACK_FAILURE                  0x82AA0005
#define CMN_E_CSP_OUTPROC_FAILURE               0x82AA0006
#define CMN_E_MARSHAL_LIMIT_EXCEEDED            0x82AA0007
#define DM_E_SESSION_ABORT                      0x82AB0000
#define DM_E_SERVER_AUTH_FAILURE                0x82AB0002
#define DM_E_UI_ALERT_REJECT                    0x82AB0004
#define DM_E_UNEXPECTED_NODE_TYPE               0x82AB0005
#define DM_E_UI_ALERT_CANCEL                    0x82AB0006
#define DM_E_CMD_BYPASSED                       0x82AB0007
#define DM_E_UI_ALERT_TIMEOUT                   0x82AB0008
#define DM_E_UI_ALERT_TEXT_TOO_LARGE            0x82AB0009
#define DM_E_PUSH_MSG_PARSE_ERROR               0x82AB000B
#define DM_E_PUSH_MSG_INITIATION_NOTFOUND       0x82AB000C
#define DM_E_KEEPALIVE_MSG_BEING_PROCESSED      0x82AB000D
#define DM_E_RESULTS_SPAN_MULTIPLE_MESSAGES     0x82AB000E
#define DM_NGC_KEY_NOT_FOUND                    0x82AB000F
#define DM_NGC_AAD_KEY_IDENTIFIER_MISMATCH      0x82AB0010
#define DM_NGC_MANAGED_BY_GP                    0x82AB0011
#define OMADM_E_SYNCHDR_ERROR                   0x82AC0000
#define OMADM_E_SESSION_ABORT_407_RECEIVED      0x82AC0001
#define OMADM_E_SESSION_ABORT_BY_USER           0x82AC0002
#define OMADM_E_SESSION_ABORT_ROAMING           0x82AC0004
#define OMADM_E_SESSION_ABORT_INCORRECT_HMAC    0x82AC0005
#define OMADM_E_SESSION_ABORT_BY_DELETE         0x82AC0006
#define OMADM_E_SESSION_ABORT_NO_MORE_RETRY     0x82AC0007
#define OMADM_E_SESSION_ABORT_NO_DATA_RECEIVED  0x82AC0008
#define OMADM_E_SESSION_NOT_ALLOWED             0x82AC0009
#define OMADM_E_SSLCERTCRITERIA_INVALID         0x82AC000A
#define OMADM_E_SESSION_ABORT_401_RECEIVED      0x82AC0191
#define OMADM_E_SESSION_ABORT_403_RECEIVED      0x82AC0193
#define OMADM_E_SESSION_ABORT_404_RECEIVED      0x82AC0194
#define OMADM_E_SESSION_ABORT_413_RECEIVED      0x82AC019D
#define OMADM_E_SESSION_ABORT_UNEXPECTED_HTTP_S 0x82AC019E
#define OMADM_E_SESSION_RETRIED_HTTP_STATUS     0x82AC0200
#define OMADM_E_SESSION_ABORT_UNEXPECTED_CONTEN 0x82AC0201
#define ZIPCONTAINER_E_INVALIDOBJECT            0x82AD0000
#define ZIPCONTAINER_E_STREAMNOTAVAILABLE       0x82AD0001
#define ZIPCONTAINER_E_ZIPDATAERROR             0x82AD0002
#define ZIPCONTAINER_E_CORRUPTED                0x82AD0003
#define ZIPCONTAINER_E_INVALIDFILENAME          0x82AD0004
#define ZIPCONTAINER_E_NOTFOUND                 0x82AD0005
#define ZIPCONTAINER_E_NOTINITIALIZED           0x82AD0006
#define ZIPCONTAINER_E_READONLY                 0x82AD0007
#define ZIPCONTAINER_E_INVALIDARCHIVE           0x82AD0008
#define ZIPCONTAINER_E_UNSUPPORTEDCOMPRESSIONME 0x82AD0009
#define ZIPCONTAINER_E_INVALIDSTREAM            0x82AD000B
#define ZIPCONTAINER_E_FORMATNOTSUPPORTED       0x82AD000C
#define ZIPCONTAINER_E_INVALIDITEM              0x82AD000D
#define ZIPCONTAINER_E_CANNOT_LOAD_ZLIB_DLL     0x82AD000F
#define ZIPCONTAINER_E_MISSING_ZLIB_DLL_EXPORT  0x82AD0010
#define ENROLLMENT_E_ALREADY_ENROLLED           0x82AE0004

static ErrorCodeItem ec_dme_items[] = {
    REGCODE(CMN_E_NOT_YET_INITIALIZED)
    REGCODE(CMN_E_BAD_XML)
    REGCODE(CMN_E_ALREADY_EXISTS)
    REGCODE(CMN_E_INTEGER_OVERFLOW)
    REGCODE(CMN_E_INTEGER_UNDERFLOW)
    REGCODE(CMN_E_ROLLBACK_FAILURE)
    REGCODE(CMN_E_CSP_OUTPROC_FAILURE)
    REGCODE(CMN_E_MARSHAL_LIMIT_EXCEEDED)
    REGCODE(DM_E_SESSION_ABORT)
    REGCODE(DM_E_SERVER_AUTH_FAILURE)
    REGCODE(DM_E_UI_ALERT_REJECT)
    REGCODE(DM_E_UNEXPECTED_NODE_TYPE)
    REGCODE(DM_E_UI_ALERT_CANCEL)
    REGCODE(DM_E_CMD_BYPASSED)
    REGCODE(DM_E_UI_ALERT_TIMEOUT)
    REGCODE(DM_E_UI_ALERT_TEXT_TOO_LARGE)
    REGCODE(DM_E_PUSH_MSG_PARSE_ERROR)
    REGCODE(DM_E_PUSH_MSG_INITIATION_NOTFOUND)
    REGCODE(DM_E_KEEPALIVE_MSG_BEING_PROCESSED)
    REGCODE(DM_E_RESULTS_SPAN_MULTIPLE_MESSAGES)
    REGCODE(DM_NGC_KEY_NOT_FOUND)
    REGCODE(DM_NGC_AAD_KEY_IDENTIFIER_MISMATCH)
    REGCODE(DM_NGC_MANAGED_BY_GP)
    REGCODE(OMADM_E_SYNCHDR_ERROR)
    REGCODE(OMADM_E_SESSION_ABORT_407_RECEIVED)
    REGCODE(OMADM_E_SESSION_ABORT_BY_USER)
    REGCODE(OMADM_E_SESSION_ABORT_ROAMING)
    REGCODE(OMADM_E_SESSION_ABORT_INCORRECT_HMAC)
    REGCODE(OMADM_E_SESSION_ABORT_BY_DELETE)
    REGCODE(OMADM_E_SESSION_ABORT_NO_MORE_RETRY)
    REGCODE(OMADM_E_SESSION_ABORT_NO_DATA_RECEIVED)
    REGCODE(OMADM_E_SESSION_NOT_ALLOWED)
    REGCODE(OMADM_E_SSLCERTCRITERIA_INVALID)
    REGCODE(OMADM_E_SESSION_ABORT_401_RECEIVED)
    REGCODE(OMADM_E_SESSION_ABORT_403_RECEIVED)
    REGCODE(OMADM_E_SESSION_ABORT_404_RECEIVED)
    REGCODE(OMADM_E_SESSION_ABORT_413_RECEIVED)
    REGCODE(OMADM_E_SESSION_ABORT_UNEXPECTED_HTTP_S)
    REGCODE(OMADM_E_SESSION_RETRIED_HTTP_STATUS)
    REGCODE(OMADM_E_SESSION_ABORT_UNEXPECTED_CONTEN)
    REGCODE(ZIPCONTAINER_E_INVALIDOBJECT)
    REGCODE(ZIPCONTAINER_E_STREAMNOTAVAILABLE)
    REGCODE(ZIPCONTAINER_E_ZIPDATAERROR)
    REGCODE(ZIPCONTAINER_E_CORRUPTED)
    REGCODE(ZIPCONTAINER_E_INVALIDFILENAME)
    REGCODE(ZIPCONTAINER_E_NOTFOUND)
    REGCODE(ZIPCONTAINER_E_NOTINITIALIZED)
    REGCODE(ZIPCONTAINER_E_READONLY)
    REGCODE(ZIPCONTAINER_E_INVALIDARCHIVE)
    REGCODE(ZIPCONTAINER_E_UNSUPPORTEDCOMPRESSIONME)
    REGCODE(ZIPCONTAINER_E_INVALIDSTREAM)
    REGCODE(ZIPCONTAINER_E_FORMATNOTSUPPORTED)
    REGCODE(ZIPCONTAINER_E_INVALIDITEM)
    REGCODE(ZIPCONTAINER_E_CANNOT_LOAD_ZLIB_DLL)
    REGCODE(ZIPCONTAINER_E_MISSING_ZLIB_DLL_EXPORT)
    REGCODE(ENROLLMENT_E_ALREADY_ENROLLED)
};

static LPTSTR dme_code2msg(DWORD dwCode)
{
    LPTSTR result = NULL;

    if (hModCertUtil)
    {
        UINT uID = dwCode;

        if (uID < 0x82AB0000)
        {
            uID = (uID & 0xFFFF) + 0xF000;
        }
        else if (uID < 0x82AC0000)
        {
            uID = (uID & 0xFFFF) + 0xF100;
        }
        else if (uID < 0x82AC0100)
        {
            uID = (uID & 0xFFFF) + 0xF200;
        }
        else if (uID < 0x82AD0000)
        {
            uID = (uID & 0xFFFF) + 0xF100;
        }
        else if (uID < 0x82AE0000)
        {
            uID = (uID & 0xFFFF) + 0xF300;
        }
        else
        {
            uID = (uID & 0xFFFF) + 0xF400;
        }

        if (0 != uID)
        {
            result = (LPTSTR)LocalAlloc(LPTR, MAX_MSG_LEN * sizeof (TCHAR));
            if (result)
            {
                LoadString(hModCertUtil, uID, result, MAX_MSG_LEN);
            }
        }
    }

    return result;
}

static void dme_freemsg(LPTSTR lpMessage)
{
    LocalFree(lpMessage);
}

void EcRegDme(ErrorCodeSet *pecs)
{
    pecs->lpName = TEXT("DME");
    pecs->pfnMessageFromCode = dme_code2msg;
    pecs->pfnFreeMessage = dme_freemsg;
    pecs->items = ec_dme_items;
    pecs->dwCodeCount = ARRAYSIZE(ec_dme_items);
}

void EcUnregDme()
{
    /* Ignore */
}

