#include "../ecf.h"
#include <errno.h>

static ErrorCodeItem ec_errno_items[] = {
    REGCODE(EPERM)
    REGCODE(ENOENT)
    REGCODE(ESRCH)
    REGCODE(EINTR)
    REGCODE(EIO)
    REGCODE(ENXIO)
    REGCODE(E2BIG)
    REGCODE(ENOEXEC)
    REGCODE(EBADF)
    REGCODE(ECHILD)
    REGCODE(EAGAIN)
    REGCODE(ENOMEM)
    REGCODE(EACCES)
    REGCODE(EFAULT)
    REGCODE(EBUSY)
    REGCODE(EEXIST)
    REGCODE(EXDEV)
    REGCODE(ENODEV)
    REGCODE(ENOTDIR)
    REGCODE(EISDIR)
    REGCODE(EINVAL)
    REGCODE(ENFILE)
    REGCODE(EMFILE)
    REGCODE(ENOTTY)
    REGCODE(EFBIG)
    REGCODE(ENOSPC)
    REGCODE(ESPIPE)
    REGCODE(EROFS)
    REGCODE(EMLINK)
    REGCODE(EPIPE)
    REGCODE(EDOM)
    REGCODE(ERANGE)
    REGCODE(EDEADLK)
    REGCODE(ENAMETOOLONG)
    REGCODE(ENOLCK)
    REGCODE(ENOSYS)
    REGCODE(ENOTEMPTY)
    REGCODE(EILSEQ)
    REGCODE(STRUNCATE)
    REGCODE(EADDRINUSE)
    REGCODE(EADDRNOTAVAIL)
    REGCODE(EAFNOSUPPORT)
    REGCODE(EALREADY)
    REGCODE(EBADMSG)
    REGCODE(ECANCELED)
    REGCODE(ECONNABORTED)
    REGCODE(ECONNREFUSED)
    REGCODE(ECONNRESET)
    REGCODE(EDESTADDRREQ)
    REGCODE(EHOSTUNREACH)
    REGCODE(EIDRM)
    REGCODE(EINPROGRESS)
    REGCODE(EISCONN)
    REGCODE(ELOOP)
    REGCODE(EMSGSIZE)
    REGCODE(ENETDOWN)
    REGCODE(ENETRESET)
    REGCODE(ENETUNREACH)
    REGCODE(ENOBUFS)
    REGCODE(ENODATA)
    REGCODE(ENOLINK)
    REGCODE(ENOMSG)
    REGCODE(ENOPROTOOPT)
    REGCODE(ENOSR)
    REGCODE(ENOSTR)
    REGCODE(ENOTCONN)
    REGCODE(ENOTRECOVERABLE)
    REGCODE(ENOTSOCK)
    REGCODE(ENOTSUP)
    REGCODE(EOPNOTSUPP)
    REGCODE(EOTHER)
    REGCODE(EOVERFLOW)
    REGCODE(EOWNERDEAD)
    REGCODE(EPROTO)
    REGCODE(EPROTONOSUPPORT)
    REGCODE(EPROTOTYPE)
    REGCODE(ETIME)
    REGCODE(ETIMEDOUT)
    REGCODE(ETXTBSY)
    REGCODE(EWOULDBLOCK)
};

static LPTSTR errno_code2msg(DWORD dwCode)
{
    return _tcserror(dwCode);
}

static void errno_freemsg(LPTSTR lpMessage)
{
    /* Ignore */
}

void EcRegErrno(ErrorCodeSet *pecs)
{
    pecs->lpName = TEXT("errno");
    pecs->pfnMessageFromCode = errno_code2msg;
    pecs->pfnFreeMessage = errno_freemsg;
    pecs->items = ec_errno_items;
    pecs->dwCodeCount = ARRAYSIZE(ec_errno_items);
}

void EcUnregErrno()
{
    /* Ignore */
}

