#include "../ecf.h"

#ifndef MENROLL_E_DEVICE_MESSAGE_FORMAT_ERROR
#define MENROLL_E_DEVICE_MESSAGE_FORMAT_ERROR   0x80180001
#endif
#ifndef MENROLL_E_DEVICE_AUTHENTICATION_ERROR
#define MENROLL_E_DEVICE_AUTHENTICATION_ERROR   0x80180002
#endif
#ifndef MENROLL_E_DEVICE_AUTHORIZATION_ERROR
#define MENROLL_E_DEVICE_AUTHORIZATION_ERROR    0x80180003
#endif
#ifndef MENROLL_E_DEVICE_CERTIFCATEREQUEST_ERRO
#define MENROLL_E_DEVICE_CERTIFCATEREQUEST_ERRO 0x80180004
#endif
#ifndef MENROLL_E_DEVICE_CONFIGMGRSERVER_ERROR
#define MENROLL_E_DEVICE_CONFIGMGRSERVER_ERROR  0x80180005
#endif
#ifndef MENROLL_E_DEVICE_INTERNALSERVICE_ERROR
#define MENROLL_E_DEVICE_INTERNALSERVICE_ERROR  0x80180006
#endif
#ifndef MENROLL_E_DEVICE_INVALIDSECURITY_ERROR
#define MENROLL_E_DEVICE_INVALIDSECURITY_ERROR  0x80180007
#endif
#ifndef MENROLL_E_DEVICE_UNKNOWN_ERROR
#define MENROLL_E_DEVICE_UNKNOWN_ERROR          0x80180008
#endif
#ifndef MENROLL_E_ENROLLMENT_IN_PROGRESS
#define MENROLL_E_ENROLLMENT_IN_PROGRESS        0x80180009
#endif
#ifndef MENROLL_E_DEVICE_ALREADY_ENROLLED
#define MENROLL_E_DEVICE_ALREADY_ENROLLED       0x8018000A
#endif
#ifndef MENROLL_E_DEVICE_NOT_ENROLLED
#define MENROLL_E_DEVICE_NOT_ENROLLED           0x8018000B
#endif
#ifndef MENROLL_E_DISCOVERY_SEC_CERT_DATE_INVAL
#define MENROLL_E_DISCOVERY_SEC_CERT_DATE_INVAL 0x8018000D
#endif
#ifndef MENROLL_E_PASSWORD_NEEDED
#define MENROLL_E_PASSWORD_NEEDED               0x8018000E
#endif
#ifndef MENROLL_E_WAB_ERROR
#define MENROLL_E_WAB_ERROR                     0x8018000F
#endif
#ifndef MENROLL_E_CONNECTIVITY
#define MENROLL_E_CONNECTIVITY                  0x80180010
#endif
#ifndef MENROLL_E_INVALIDSSLCERT
#define MENROLL_E_INVALIDSSLCERT                0x80180012
#endif
#ifndef MENROLL_E_DEVICECAPREACHED
#define MENROLL_E_DEVICECAPREACHED              0x80180013
#endif
#ifndef MENROLL_E_DEVICENOTSUPPORTED
#define MENROLL_E_DEVICENOTSUPPORTED            0x80180014
#endif
#ifndef MENROLL_E_NOTSUPPORTED
#define MENROLL_E_NOTSUPPORTED                  0x80180015
#endif
#ifndef MENROLL_E_NOTELIGIBLETORENEW
#define MENROLL_E_NOTELIGIBLETORENEW            0x80180016
#endif
#ifndef MENROLL_E_INMAINTENANCE
#define MENROLL_E_INMAINTENANCE                 0x80180017
#endif
#ifndef MENROLL_E_USERLICENSE
#define MENROLL_E_USERLICENSE                   0x80180018
#endif
#ifndef MENROLL_E_ENROLLMENTDATAINVALID
#define MENROLL_E_ENROLLMENTDATAINVALID         0x80180019
#endif
#ifndef MENROLL_E_INSECUREREDIRECT
#define MENROLL_E_INSECUREREDIRECT              0x8018001A
#endif
#ifndef MENROLL_E_PLATFORM_WRONG_STATE
#define MENROLL_E_PLATFORM_WRONG_STATE          0x8018001B
#endif
#ifndef MENROLL_E_PLATFORM_LICENSE_ERROR
#define MENROLL_E_PLATFORM_LICENSE_ERROR        0x8018001C
#endif
#ifndef MENROLL_E_PLATFORM_UNKNOWN_ERROR
#define MENROLL_E_PLATFORM_UNKNOWN_ERROR        0x8018001D
#endif
#ifndef MENROLL_E_PROV_CSP_CERTSTORE
#define MENROLL_E_PROV_CSP_CERTSTORE            0x8018001E
#endif
#ifndef MENROLL_E_PROV_CSP_W7
#define MENROLL_E_PROV_CSP_W7                   0x8018001F
#endif
#ifndef MENROLL_E_PROV_CSP_DMCLIENT
#define MENROLL_E_PROV_CSP_DMCLIENT             0x80180020
#endif
#ifndef MENROLL_E_PROV_CSP_PFW
#define MENROLL_E_PROV_CSP_PFW                  0x80180021
#endif
#ifndef MENROLL_E_PROV_CSP_MISC
#define MENROLL_E_PROV_CSP_MISC                 0x80180022
#endif
#ifndef MENROLL_E_PROV_UNKNOWN
#define MENROLL_E_PROV_UNKNOWN                  0x80180023
#endif
#ifndef MENROLL_E_PROV_SSLCERTNOTFOUND
#define MENROLL_E_PROV_SSLCERTNOTFOUND          0x80180024
#endif
#ifndef MENROLL_E_PROV_CSP_APPMGMT
#define MENROLL_E_PROV_CSP_APPMGMT              0x80180025
#endif
#ifndef MENROLL_E_DEVICE_MANAGEMENT_BLOCKED
#define MENROLL_E_DEVICE_MANAGEMENT_BLOCKED     0x80180026
#endif
#ifndef MENROLL_E_CERTPOLICY_PRIVATEKEYCREATION
#define MENROLL_E_CERTPOLICY_PRIVATEKEYCREATION 0x80180027
#endif
#ifndef MENROLL_E_CERTAUTH_FAILED_TO_FIND_CERT
#define MENROLL_E_CERTAUTH_FAILED_TO_FIND_CERT  0x80180028
#endif
#ifndef MENROLL_E_EMPTY_MESSAGE
#define MENROLL_E_EMPTY_MESSAGE                 0x80180029
#endif

static ErrorCodeItem ec_mdm_items[] = {
    REGCODE(MENROLL_E_DEVICE_MESSAGE_FORMAT_ERROR)
    REGCODE(MENROLL_E_DEVICE_AUTHENTICATION_ERROR)
    REGCODE(MENROLL_E_DEVICE_AUTHORIZATION_ERROR)
    REGCODE(MENROLL_E_DEVICE_CERTIFCATEREQUEST_ERRO)
    REGCODE(MENROLL_E_DEVICE_CONFIGMGRSERVER_ERROR)
    REGCODE(MENROLL_E_DEVICE_INTERNALSERVICE_ERROR)
    REGCODE(MENROLL_E_DEVICE_INVALIDSECURITY_ERROR)
    REGCODE(MENROLL_E_DEVICE_UNKNOWN_ERROR)
    REGCODE(MENROLL_E_ENROLLMENT_IN_PROGRESS)
    REGCODE(MENROLL_E_DEVICE_ALREADY_ENROLLED)
    REGCODE(MENROLL_E_DEVICE_NOT_ENROLLED)
    REGCODE(MENROLL_E_DISCOVERY_SEC_CERT_DATE_INVAL)
    REGCODE(MENROLL_E_PASSWORD_NEEDED)
    REGCODE(MENROLL_E_WAB_ERROR)
    REGCODE(MENROLL_E_CONNECTIVITY)
    REGCODE(MENROLL_E_INVALIDSSLCERT)
    REGCODE(MENROLL_E_DEVICECAPREACHED)
    REGCODE(MENROLL_E_DEVICENOTSUPPORTED)
    REGCODE(MENROLL_E_NOTSUPPORTED)
    REGCODE(MENROLL_E_NOTELIGIBLETORENEW)
    REGCODE(MENROLL_E_INMAINTENANCE)
    REGCODE(MENROLL_E_USERLICENSE)
    REGCODE(MENROLL_E_ENROLLMENTDATAINVALID)
    REGCODE(MENROLL_E_INSECUREREDIRECT)
    REGCODE(MENROLL_E_PLATFORM_WRONG_STATE)
    REGCODE(MENROLL_E_PLATFORM_LICENSE_ERROR)
    REGCODE(MENROLL_E_PLATFORM_UNKNOWN_ERROR)
    REGCODE(MENROLL_E_PROV_CSP_CERTSTORE)
    REGCODE(MENROLL_E_PROV_CSP_W7)
    REGCODE(MENROLL_E_PROV_CSP_DMCLIENT)
    REGCODE(MENROLL_E_PROV_CSP_PFW)
    REGCODE(MENROLL_E_PROV_CSP_MISC)
    REGCODE(MENROLL_E_PROV_UNKNOWN)
    REGCODE(MENROLL_E_PROV_SSLCERTNOTFOUND)
    REGCODE(MENROLL_E_PROV_CSP_APPMGMT)
    REGCODE(MENROLL_E_DEVICE_MANAGEMENT_BLOCKED)
    REGCODE(MENROLL_E_CERTPOLICY_PRIVATEKEYCREATION)
    REGCODE(MENROLL_E_CERTAUTH_FAILED_TO_FIND_CERT)
    REGCODE(MENROLL_E_EMPTY_MESSAGE)
};

static LPTSTR mdm_code2msg(DWORD dwCode)
{
    return MsgFromSys(FORMAT_MESSAGE_FROM_SYSTEM, NULL, dwCode);
}

static void mdm_freemsg(LPTSTR lpMessage)
{
    LocalFree(lpMessage);
}

void EcRegMdm(ErrorCodeSet *pecs)
{
    pecs->lpName = TEXT("MDM");
    pecs->pfnMessageFromCode = mdm_code2msg;
    pecs->pfnFreeMessage = mdm_freemsg;
    pecs->items = ec_mdm_items;
    pecs->dwCodeCount = ARRAYSIZE(ec_mdm_items);
}

void EcUnregMdm()
{
    /* Ignore */
}

