#include "../ecf.h"
#include <wininet.h>

#ifndef ERROR_HTTP_HSTS_REDIRECT_REQUIRED
#define ERROR_HTTP_HSTS_REDIRECT_REQUIRED                   (INTERNET_ERROR_BASE + 60)
#endif
#ifndef ERROR_INTERNET_SEC_CERT_WEAK_SIGNATURE
#define ERROR_INTERNET_SEC_CERT_WEAK_SIGNATURE              (INTERNET_ERROR_BASE + 62)
#endif
#ifndef ERROR_INTERNET_CLIENT_AUTH_CERT_NEEDED_PROXY
#define ERROR_INTERNET_CLIENT_AUTH_CERT_NEEDED_PROXY        (INTERNET_ERROR_BASE + 187)
#endif
#ifndef ERROR_INTERNET_SECURE_FAILURE_PROXY
#define ERROR_INTERNET_SECURE_FAILURE_PROXY                 (INTERNET_ERROR_BASE + 188)
#endif

/* In winhttp.h but conflict */
#define ERROR_WINHTTP_CANNOT_CALL_BEFORE_OPEN               (INTERNET_ERROR_BASE + 100)
#define ERROR_WINHTTP_CANNOT_CALL_BEFORE_SEND               (INTERNET_ERROR_BASE + 101)
#define ERROR_WINHTTP_CANNOT_CALL_AFTER_SEND                (INTERNET_ERROR_BASE + 102)
#define ERROR_WINHTTP_CANNOT_CALL_AFTER_OPEN                (INTERNET_ERROR_BASE + 103)
#define ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR              (INTERNET_ERROR_BASE + 178)
#define ERROR_WINHTTP_SECURE_CERT_WRONG_USAGE               (INTERNET_ERROR_BASE + 179)
#define ERROR_WINHTTP_AUTODETECTION_FAILED                  (INTERNET_ERROR_BASE + 180)
#define ERROR_WINHTTP_HEADER_COUNT_EXCEEDED                 (INTERNET_ERROR_BASE + 181)
#define ERROR_WINHTTP_HEADER_SIZE_OVERFLOW                  (INTERNET_ERROR_BASE + 182)
#define ERROR_WINHTTP_CHUNKED_ENCODING_HEADER_SIZE_OVERFLOW (INTERNET_ERROR_BASE + 183)
#define ERROR_WINHTTP_RESPONSE_DRAIN_OVERFLOW               (INTERNET_ERROR_BASE + 184)
#define ERROR_WINHTTP_CLIENT_CERT_NO_PRIVATE_KEY            (INTERNET_ERROR_BASE + 185)
#define ERROR_WINHTTP_CLIENT_CERT_NO_ACCESS_PRIVATE_KEY     (INTERNET_ERROR_BASE + 186)

static ErrorCodeItem ec_winhttp_items[] = {
    REGCODE(ERROR_INTERNET_OUT_OF_HANDLES)
    REGCODE(ERROR_INTERNET_TIMEOUT)
    REGCODE(ERROR_INTERNET_EXTENDED_ERROR)
    REGCODE(ERROR_INTERNET_INTERNAL_ERROR)
    REGCODE(ERROR_INTERNET_INVALID_URL)
    REGCODE(ERROR_INTERNET_UNRECOGNIZED_SCHEME)
    REGCODE(ERROR_INTERNET_NAME_NOT_RESOLVED)
    REGCODE(ERROR_INTERNET_PROTOCOL_NOT_FOUND)
    REGCODE(ERROR_INTERNET_INVALID_OPTION)
    REGCODE(ERROR_INTERNET_BAD_OPTION_LENGTH)
    REGCODE(ERROR_INTERNET_OPTION_NOT_SETTABLE)
    REGCODE(ERROR_INTERNET_SHUTDOWN)
    REGCODE(ERROR_INTERNET_INCORRECT_USER_NAME)
    REGCODE(ERROR_INTERNET_INCORRECT_PASSWORD)
    REGCODE(ERROR_INTERNET_LOGIN_FAILURE)
    REGCODE(ERROR_INTERNET_INVALID_OPERATION)
    REGCODE(ERROR_INTERNET_OPERATION_CANCELLED)
    REGCODE(ERROR_INTERNET_INCORRECT_HANDLE_TYPE)
    REGCODE(ERROR_INTERNET_INCORRECT_HANDLE_STATE)
    REGCODE(ERROR_INTERNET_NOT_PROXY_REQUEST)
    REGCODE(ERROR_INTERNET_REGISTRY_VALUE_NOT_FOUND)
    REGCODE(ERROR_INTERNET_BAD_REGISTRY_PARAMETER)
    REGCODE(ERROR_INTERNET_NO_DIRECT_ACCESS)
    REGCODE(ERROR_INTERNET_NO_CONTEXT)
    REGCODE(ERROR_INTERNET_NO_CALLBACK)
    REGCODE(ERROR_INTERNET_REQUEST_PENDING)
    REGCODE(ERROR_INTERNET_INCORRECT_FORMAT)
    REGCODE(ERROR_INTERNET_ITEM_NOT_FOUND)
    REGCODE(ERROR_INTERNET_CANNOT_CONNECT)
    REGCODE(ERROR_INTERNET_CONNECTION_ABORTED)
    REGCODE(ERROR_INTERNET_CONNECTION_RESET)
    REGCODE(ERROR_INTERNET_FORCE_RETRY)
    REGCODE(ERROR_INTERNET_INVALID_PROXY_REQUEST)
    REGCODE(ERROR_INTERNET_NEED_UI)
    REGCODE(ERROR_INTERNET_HANDLE_EXISTS)
    REGCODE(ERROR_INTERNET_SEC_CERT_DATE_INVALID)
    REGCODE(ERROR_INTERNET_SEC_CERT_CN_INVALID)
    REGCODE(ERROR_INTERNET_HTTP_TO_HTTPS_ON_REDIR)
    REGCODE(ERROR_INTERNET_HTTPS_TO_HTTP_ON_REDIR)
    REGCODE(ERROR_INTERNET_MIXED_SECURITY)
    REGCODE(ERROR_INTERNET_CHG_POST_IS_NON_SECURE)
    REGCODE(ERROR_INTERNET_POST_IS_NON_SECURE)
    REGCODE(ERROR_INTERNET_CLIENT_AUTH_CERT_NEEDED)
    REGCODE(ERROR_INTERNET_INVALID_CA)
    REGCODE(ERROR_INTERNET_CLIENT_AUTH_NOT_SETUP)
    REGCODE(ERROR_INTERNET_ASYNC_THREAD_FAILED)
    REGCODE(ERROR_INTERNET_REDIRECT_SCHEME_CHANGE)
    REGCODE(ERROR_INTERNET_DIALOG_PENDING)
    REGCODE(ERROR_INTERNET_RETRY_DIALOG)
    REGCODE(ERROR_INTERNET_HTTPS_HTTP_SUBMIT_REDIR)
    REGCODE(ERROR_INTERNET_INSERT_CDROM)
    REGCODE(ERROR_INTERNET_FORTEZZA_LOGIN_NEEDED)
    REGCODE(ERROR_INTERNET_SEC_CERT_ERRORS)
    REGCODE(ERROR_INTERNET_SEC_CERT_NO_REV)
    REGCODE(ERROR_INTERNET_SEC_CERT_REV_FAILED)
    REGCODE(ERROR_HTTP_HSTS_REDIRECT_REQUIRED)
    REGCODE(ERROR_INTERNET_SEC_CERT_WEAK_SIGNATURE)
    REGCODE(ERROR_WINHTTP_CANNOT_CALL_BEFORE_OPEN)
    REGCODE(ERROR_WINHTTP_CANNOT_CALL_BEFORE_SEND)
    REGCODE(ERROR_WINHTTP_CANNOT_CALL_AFTER_SEND)
    REGCODE(ERROR_WINHTTP_CANNOT_CALL_AFTER_OPEN)
    REGCODE(ERROR_FTP_TRANSFER_IN_PROGRESS)
    REGCODE(ERROR_FTP_DROPPED)
    REGCODE(ERROR_FTP_NO_PASSIVE_MODE)
    REGCODE(ERROR_GOPHER_PROTOCOL_ERROR)
    REGCODE(ERROR_GOPHER_NOT_FILE)
    REGCODE(ERROR_GOPHER_DATA_ERROR)
    REGCODE(ERROR_GOPHER_END_OF_DATA)
    REGCODE(ERROR_GOPHER_INVALID_LOCATOR)
    REGCODE(ERROR_GOPHER_INCORRECT_LOCATOR_TYPE)
    REGCODE(ERROR_GOPHER_NOT_GOPHER_PLUS)
    REGCODE(ERROR_GOPHER_ATTRIBUTE_NOT_FOUND)
    REGCODE(ERROR_GOPHER_UNKNOWN_LOCATOR)
    REGCODE(ERROR_HTTP_HEADER_NOT_FOUND)
    REGCODE(ERROR_HTTP_DOWNLEVEL_SERVER)
    REGCODE(ERROR_HTTP_INVALID_SERVER_RESPONSE)
    REGCODE(ERROR_HTTP_INVALID_HEADER)
    REGCODE(ERROR_HTTP_INVALID_QUERY_REQUEST)
    REGCODE(ERROR_HTTP_HEADER_ALREADY_EXISTS)
    REGCODE(ERROR_HTTP_REDIRECT_FAILED)
    REGCODE(ERROR_HTTP_NOT_REDIRECTED)
    REGCODE(ERROR_HTTP_COOKIE_NEEDS_CONFIRMATION)
    REGCODE(ERROR_HTTP_COOKIE_DECLINED)
    REGCODE(ERROR_HTTP_REDIRECT_NEEDS_CONFIRMATION)
    REGCODE(ERROR_INTERNET_SECURITY_CHANNEL_ERROR)
    REGCODE(ERROR_INTERNET_UNABLE_TO_CACHE_FILE)
    REGCODE(ERROR_INTERNET_TCPIP_NOT_INSTALLED)
    REGCODE(ERROR_INTERNET_DISCONNECTED)
    REGCODE(ERROR_INTERNET_SERVER_UNREACHABLE)
    REGCODE(ERROR_INTERNET_PROXY_SERVER_UNREACHABLE)
    REGCODE(ERROR_INTERNET_BAD_AUTO_PROXY_SCRIPT)
    REGCODE(ERROR_INTERNET_UNABLE_TO_DOWNLOAD_SCRIPT)
    REGCODE(ERROR_INTERNET_SEC_INVALID_CERT)
    REGCODE(ERROR_INTERNET_SEC_CERT_REVOKED)
    REGCODE(ERROR_INTERNET_FAILED_DUETOSECURITYCHECK)
    REGCODE(ERROR_INTERNET_NOT_INITIALIZED)
    REGCODE(ERROR_INTERNET_NEED_MSN_SSPI_PKG)
    REGCODE(ERROR_INTERNET_LOGIN_FAILURE_DISPLAY_ENTITY_BODY)
    REGCODE(ERROR_INTERNET_DECODING_FAILED)
    REGCODE(ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR)
    REGCODE(ERROR_WINHTTP_SECURE_CERT_WRONG_USAGE)
    REGCODE(ERROR_WINHTTP_AUTODETECTION_FAILED)
    REGCODE(ERROR_WINHTTP_HEADER_COUNT_EXCEEDED)
    REGCODE(ERROR_WINHTTP_HEADER_SIZE_OVERFLOW)
    REGCODE(ERROR_WINHTTP_CHUNKED_ENCODING_HEADER_SIZE_OVERFLOW)
    REGCODE(ERROR_WINHTTP_RESPONSE_DRAIN_OVERFLOW)
    REGCODE(ERROR_WINHTTP_CLIENT_CERT_NO_PRIVATE_KEY)
    REGCODE(ERROR_WINHTTP_CLIENT_CERT_NO_ACCESS_PRIVATE_KEY)
    REGCODE(ERROR_INTERNET_CLIENT_AUTH_CERT_NEEDED_PROXY)
    REGCODE(ERROR_INTERNET_SECURE_FAILURE_PROXY)
};

static LPTSTR winhttp_code2msg(DWORD dwCode)
{
    return MsgFromSys(FORMAT_MESSAGE_FROM_HMODULE, hModHttp, dwCode);
}

static void winhttp_freemsg(LPTSTR lpMessage)
{
    LocalFree(lpMessage);
}

void EcRegWinhttp(ErrorCodeSet *pecs)
{
    pecs->lpName = TEXT("WinHttp");
    pecs->pfnMessageFromCode = winhttp_code2msg;
    pecs->pfnFreeMessage = winhttp_freemsg;
    pecs->items = ec_winhttp_items;
    pecs->dwCodeCount = ARRAYSIZE(ec_winhttp_items);
}

void EcUnregWinhttp()
{
    /* Ignore */
}

